# -*- coding: utf-8 -*-
"""sensor anomaly analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IPy5R0E0-mcWssB-YJACf2WGPSr0YSbX
"""

from google.colab import files
uploaded = files.upload()

# import sqlite and create uniform timestamp
import sqlite3
import pandas as pd
df = pd.read_csv('Nhavi(Indapur)_Report_29_7_2026-30_7_2026.csv')
df['datetime'] = pd.to_datetime(df['date'] + ' ' + df['time'])
print(df[['date', 'time', 'datetime']].head())
print(df['datetime'].dtype)

# create sqlite database and connect it to load data
def create_connection(path):
    connection = None
    try:
        connection = sqlite3.connect(path)
        print("Connection to SQLite DB successful")
    except Error as e:
        print(f"The error '{e}' occurred")
    return connection

conn = create_connection('spectra.db')
df.to_sql('sensor_data', conn, if_exists='replace', index=False)

#take data from sqlite
query = "SELECT * FROM sensor_data ORDER BY datetime"
df = pd.read_sql(query, conn)
df['datetime'] = pd.to_datetime(df['datetime'])
df.head()

#take the sensor columns and add averages
sensor_cols = ['ACVoltage', 'TSSTemperature', 'BatteryVoltage', 'CompressorCurrent']

for col in sensor_cols:
    df[col + '_avg'] = df[col].rolling(15).mean()  # average of last 15 readings (~30 min)

df = df.dropna().reset_index(drop=True)
df.head()

# anomaly detection model
from sklearn.ensemble import IsolationForest

feature_cols = sensor_cols + [c + '_avg' for c in sensor_cols]
X = df[feature_cols]

model = IsolationForest(contamination=0.03, random_state=42)
model.fit(X)

df['is_anomaly'] = model.predict(X) == -1
print(f"Flagged {df['is_anomaly'].sum()} anomalies out of {len(df)} readings")

df[df['is_anomaly']][['datetime'] + sensor_cols].head(10)

#export to powerbi
df[['datetime'] + sensor_cols + ['is_anomaly']].to_csv('nhavi_anomalies.csv', index=False)
print("Saved!")

# download it
from google.colab import files
files.download('nhavi_anomalies.csv')